# -*- coding: utf-8 -*-
"""todolist.ipynb

Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1_zhoHUkHRp5l-EzrqUYD7QEMGwmFvvvr
"""
#
lista_tarefas = []

def adiciona_tarefa():
  while True:
    nome = input('Digite o nome da tarefa: ')
    descricao = input('Qual a descrição da tarefa: ')
    data = input('Para qual data: ')

    tarefa = {nome: {
    'descrição': descricao,'data': data
    }}

    lista_tarefas.append(tarefa)
    continuar = input('Deseja adicionar mais tarefas? \n1. SIM \n2. NÃO \n ')
    if continuar == '1':
      continue

    else:
      break

def verificar_tarefa():
  while True:
      print('-------------------------------------------')
      nome_tarefas = []
      for task in lista_tarefas:
        nome_tarefas = list(task.keys())
        print(nome_tarefas)
      print('-------------------------------------------')
      print('9. Sair:')
      print('Digite o nome da tarefa para ver mais detalhes:')
      tarefa_desejada =  input('Digite uma das opções acima: ')

      if tarefa_desejada == '9':
        break

      else:
        for task in lista_tarefas:
          if tarefa_desejada in task:
            print(task[tarefa_desejada])
  print('-------------------------------------------')


def delete():
  while True:
      print('-------------------------------------------')
      nome_tarefas = []
      for task in lista_tarefas:
        nome_tarefas = list(task.keys())
        print(nome_tarefas)

      print('-------------------------------------------')
      print('9. Sair:')
      print('Digite o nome da tarefa para deletala:')
      tarefa_desejada =  input('Digite uma das opções acima: ')

      if tarefa_desejada == '9':
        break

      else:
        for task in lista_tarefas:
          if tarefa_desejada in task:
            print('-------------------------------------------')
            print(task)
            confirma =  input('Você realmente deseja deletar a tarefa acima? \n1. SIM \n2. NÃO \n ')
            if confirma == '1':
              lista_tarefas.remove(task)

              print(f'Nova lista de tarefas: {lista_tarefas}')
              break

            else:
              continue

def main():
  while True:
    print('/n')
    print('Porfavor sececione uma das opções a baixo: ')
    print('-------------------------------------------')
    print('1. Adicione uma nova tarefa:')
    print('2. Deletar uma tarefa:')
    print('3. Listar tarefas')
    print('4. Sair')
    tarefa = None

    escolher_tarefa = input('Escolha uma das opções acima digitando de 1 a 4: ')


    if escolher_tarefa == '1':
      adiciona_tarefa()
      
    elif escolher_tarefa == '2':
      delete()
      
    elif escolher_tarefa == '3':
      verificar_tarefa()
      
    elif escolher_tarefa == '4':
      break

    else:
      continue
    
    
    
if __name__ == '__main__':
  main()
